# Generated by Django 2.1.7 on 2019-07-14 14:36

from django.db import migrations, models
import todo_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=todo_list.models.generate_key, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('to_do_list', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'to_do_list',
            },
        ),
    ]
