version: "2"

services:
  todo-list-app:
    build: .
    image: todo-list-app:latest
    hostname: todo-list-app
    privileged: true
    restart: always
    volumes:
      - ./src:/root
    ports:
      - 18888:8888
    command: sh -c '/root/run.sh'
    env_file:
      - .env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
